//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ADMIN
    {
        [Required(ErrorMessage = "Vui lòng nh?p ??y ?? thông tin")]
        public string username { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p ??y ?? thông tin")]
        public string password { get; set; }
    }
}
