//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGDIEM
    {
        public int BangDiemID { get; set; }
        public Nullable<int> ChiTietID { get; set; }
        public Nullable<int> HocVienID { get; set; }
        public string HoTen { get; set; }
        public Nullable<decimal> Diem1 { get; set; }
        public Nullable<decimal> Diem2 { get; set; }
        public Nullable<decimal> Diem3 { get; set; }
        public Nullable<byte> TongDiem { get; set; }
        public string XepLoai { get; set; }
        public Nullable<byte> LanThi { get; set; }
    
        public virtual CHITIETKHOAHOC CHITIETKHOAHOC { get; set; }
        public virtual HOCVIEN HOCVIEN { get; set; }
    }
}
