//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGHOC()
        {
            this.CHITIETKHOAHOCs = new HashSet<CHITIETKHOAHOC>();
        }
    
        public string PhongHocId { get; set; }
        public string LoaiPhongHoc { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> SucChuaPhongHoc { get; set; }
        public string TenPhongHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKHOAHOC> CHITIETKHOAHOCs { get; set; }
    }
}
