//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class RAOVAT
    {
        public RAOVAT()
        {
            HINHANH1 = "~/Content/img/upload-i.jpg";
        }
        [Display(Name = "Mã Tin")]
        public int MATIN { get; set; }
        [Display(Name = "Mã Trạng Thái")]
        public int MATRANGTHAI { get; set; }
        [Display(Name = "Mã Loại")]
        public int MALOAI { get; set; }
        [Display(Name = "Mã Tình Trạng")]
        public int MATINHTRANG { get; set; }
        [Display(Name = "Mã Loại Tin")]
        public int MALOAITIN { get; set; }
        [Display(Name = "Mã Hình Thức")]
        public int MAHINHTHUC { get; set; }
        [Display(Name = "Mã Người Dùng")]
        public int MANGUOIDUNG { get; set; }
        [Display(Name = "Tiêu Đề")]
        public string TIEUDE { get; set; }
        [Display(Name = "Hình Ảnh")]
        public string HINHANH1 { get; set; }
        [Display(Name = "Nội Dung")]
        public string NOIDUNG { get; set; }
        [Display(Name = "Ngày Giờ Đăng")]
        public Nullable<System.DateTime> NGAYGIODANG { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0 vnđ}")]
        [Display(Name = "Giá")]
        public Nullable<int> GIA { get; set; }
        [Display(Name = "Địa Chỉ")]
        public string DIACHI { get; set; }
        [Display(Name = "Ngày Hết Hạn")]
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        [Display(Name = "Mã Thành Phố")]
        public Nullable<int> MATHANHPHO { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual HINHTHUC HINHTHUC { get; set; }
        public virtual LOAITIN LOAITIN { get; set; }
        public virtual TINHTHANHPHO TINHTHANHPHO { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
        public virtual USER USER { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
